Repository pg2455/covid_p2p_simulation, pull requests merged in 2020-04, with the labels that each got.

#12 Seed / Code Splitting / Recovery / Payload
  README.md
  base.py
  config.py
  monitors.py
  run.py
  simulator.py
  toy.py
  utils.py
Labels: documentation, duplicate, enhancement

#28 Viral load
  base.py
  config.py
  plots/__init__.py
  plots/viral_load.png
  plots/viral_load_individuals.png
  plots/viral_load_plot.py
  simulator.py
  utils.py
Labels: enhancement

#62 Tuned v1
  .gitignore
  base.py
  config.py
  models/__init__.py
  models/dummy_human.py
  models/risk_models.py
  models/run.py
  monitors.py
  plots/plot_risk.py
  risk_prediction.py
  run.py
  simulator.py
  tests/full_simu_test.py
  toy.py
  track.py
  utils.py
Labels: enhancement

#60 Models
  .gitignore
  base.py
  config.py
  docs/CONTRIBUTING.md
  docs/events.md
  docs/models.md
  models/dataloader.py
  models/dummy_human.py
  models/helper.py
  models/log_risk_mapping.npy
  models/risk_models.py
  models/run.py
  plots/plot_clusters.py
  plots/plot_viral_load.py
  requirements.txt
  run.py
  simulator.py
  utils.py
Labels: enhancement

#75 Disabling Proximity factor
  base.py
  config.py
  monitors.py
  run.py
  track.py
Labels: bug

#70 Util functions to create mapping from probabilities to risk levels
  tests/test_utils_mapping.py
  utils.py
Labels: enhancement
